// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:ea5ef297-7924-4578-887e-1bca2aa39475',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'botaniclash-hosting-mobilehub-1387081416',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2qeo4xq4zcls6.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'a3f9da7a4457404dbceb85572c080bbf',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'df457187-1e4f-11e8-a529-0376e3239e30',
    'aws_project_name': 'botaniClash',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'botaniclash-mobilehub-1387081416',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_yQpumrbTB',
    'aws_user_pools_mfa_type': 'OPTIONAL',
    'aws_user_pools_web_client_id': '3gal82adn7hu9n6ko8jeqntcdv',
}

export default awsmobile;
